### ISSUE TITLE
Decode error

### ISSUE THREAD

**Issue by returnWOW** [facebookresearch/LASER#162]
Some decode error encounter when using `dl_cc_matrix.py` to download:
```
INFO 18628:root - Downloaded https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2018-22/segments/1526794867559.54/wet/CC-MAIN-20180526151207-20180526171207-00494.warc.wet.gz [200] took 316s (393.7kB/s)
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\returnwow\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\returnwow\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "G:\Data\LASER\tasks\CCMatrix\dl_cc_matrix.py", line 137, in dl_file
    raw_documents = get_documents(segment)
  File "G:\Data\LASER\tasks\CCMatrix\dl_cc_matrix.py", line 106, in get_documents
    return {d["digest"]: d["raw_content"] for d in CCSegmentsReader([segment])}
  File "G:\Data\LASER\tasks\CCMatrix\dl_cc_matrix.py", line 106, in <dictcomp>
    return {d["digest"]: d["raw_content"] for d in CCSegmentsReader([segment])}
  File "C:\Users\returnwow\AppData\Local\Programs\Python\Python38\lib\site-packages\cc_net\process_wet_file.py", line 199, in __iter__
    for doc in parse_warc_file(self.open_segment(segment), self.min_len):
  File "C:\Users\returnwow\AppData\Local\Programs\Python\Python38\lib\site-packages\cc_net\process_wet_file.py", line 132, in parse_warc_file
    for doc in group_by_docs(lines):
  File "C:\Users\returnwow\AppData\Local\Programs\Python\Python38\lib\site-packages\cc_net\process_wet_file.py", line 105, in group_by_docs
    for warc in warc_lines:
  File "C:\Users\returnwow\AppData\Local\Programs\Python\Python38\lib\site-packages\cc_net\jsonql.py", line 971, in _close_when_exhausted
    yield from file
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 406: illegal multibyte sequence
```

**Comment by gwenzek** [comment]
Can you run `import locale; locale.getpreferredencoding()` in python ?
It should say "utf8" not "gbk".

**Comment by returnWOW** [comment]
> Can you run `import locale; locale.getpreferredencoding()` in python ?
> It should say "utf8" not "gbk".

Thanks for reply, I set up default encoding to "uft-8", it's working right now.
