### ISSUE TITLE
CCMatrix - AssertionError: Print size mismatch

### ISSUE THREAD

**Issue by dvzubarev** [facebookresearch/LASER#178]
Reproduction steps for version 1.0.0:
1. Download sentences from `2019-09_0000.tsv.gz` meta file. 
    Replace in `dl` function:
   `file_list = [l.strip() for l in open_remote_file(metadata_dir + "/list.txt")]` with `file_list = ["2019-09_0000.tsv.gz"]`
2.  After that run finalize
 
   ```
2021-03-15 14:55 ERROR 19725:root - last lineno 2239378
Traceback (most recent call last):
  File "dl_cc_matrix.py", line 348, in <module>
    func_argparse.main(dl, finalize)
  File "/usr/local/lib/python3.7/dist-packages/func_argparse/__init__.py", line 29, in main
    return make_main(*fns, module=module, description=description)(sys.argv[1:])
  File "/usr/local/lib/python3.7/dist-packages/func_argparse/__init__.py", line 72, in parse_and_call
    return command(**parsed_args)
  File "dl_cc_matrix.py", line 288, in finalize
    tr(f)
  File "dl_cc_matrix.py", line 206, in transpose_file
    bt: Bitext = parser(line)
  File "dl_cc_matrix.py", line 71, in parser
    ), f"Print size mismatch expected the following columns {cls.__annotations__} got: {parts}"
AssertionError: Print size mismatch expected the following columns OrderedDict([('lang_pair', <class 'str'>), ('line_no', <class 'int'>), ('score', <class 'float'>), ('text', <class 'str'>)]) got: ['']
```
I have added code to print last processed lineno.
`zcat  data/v1.0.0/raw/2019-09_0000.tsv.gz | grep -A3 -m1 '2239378'`

```
en-lb/en        2239378 1.1287761       nt.

Now, a more interesting correspondence seems to occur in some fre
en-lb/en        6072515 1.103206        /u/?
````
You can see there are newlines in the eng. text.

**Comment by gwenzek** [comment]
I think you must have been downloading a corrupted version. There has been more recent releases in the meantime.
I recommend using http://data.statmt.org/cc-matrix/ directly instead of re-running the pipeline yourself which is very long
