### ISSUE TITLE
The embed.sh script returns AssertionError 

### ISSUE THREAD

**Issue by prasunshrestha** [facebookresearch/LASER#197]
I pulled the GitHub repo, set the environment variable 'LASER,' and downloaded the encoders and third-party software as instructed. However, whenever I run the `tasks/embed/embed.sh` script, I get the following error message:

```
couldn't find /home/prasun/projects/laser/models/wmt22/laser3-eng.v1.pt. defaulting to laser2
spm not specified, attempting default to: /home/prasun/projects/laser/models/wmt22/laser2.spm
couldn't find laser2.spm, defaulting to laser2.spm
Traceback (most recent call last):
  File "/home/prasun/projects/laser/source/embed.py", line 624, in <module>
    embed_sentences(
  File "/home/prasun/projects/laser/source/embed.py", line 487, in embed_sentences
    spm_model, spm_vocab = get_spm(encoder_path, spm_model)
  File "/home/prasun/projects/laser/source/embed.py", line 552, in get_spm
    assert (
AssertionError: Could not find /home/prasun/projects/laser/models/wmt22/laser2.spm or /home/prasun/projects/laser/models/wmt22/laser2.cvocab
```

The `wmt22` folder under `models` was never installed in the first place. How can I get the embedding script to work? Thank you!

**Comment by prasunshrestha** [comment]
Thank you, @Proyag! I downloaded the models under the `tasks/wmt22` folder, and it is working well now. I wish they had put in instructions to run the `download_models.sh`. You are a savior.
