### ISSUE TITLE
cannot install fastbpe

### ISSUE THREAD

**Issue by guangyuli-uoe** [facebookresearch/LASER#205]
hi,

i noticed that "[FastBPE](https://github.com/glample/fastBPE), fast C++ implementation of byte-pair encoding (installed automatically)"

but it seems that there is no fastbpe,

and then i tried to install it manually, but it said that :
g++ -std=c++11 -pthread -O3 fastBPE/main.cc -IfastBPE -o fast
clang: error: no such file or directory: 'fastBPE/main.cc'
clang: error: no input files

could anyone know how to solve this problem ? 
thanks !

**Comment by guangyuli-uoe** [comment]
specifically, the original problem occurred when i tried to run the bucc task:

 ./bucc.sh

Processing BUCC data in .
Traceback (most recent call last):
  File "home/LASER/source/embed.py", line 36, in <module>
    from lib.text_processing import Token, BPEfastApply, SPMApply
  File "home/LASER/source/lib/text_processing.py", line 21, in <module>
    import fastBPE
ModuleNotFoundError: No module named 'fastBPE'

**Comment by heffernankevin** [comment]
Hi @guangyuli-uoe. Can you try pulling and then re-running your above command? This dependency has been removed.

**Comment by guangyuli-uoe** [comment]
hi @heffernankevin 

the problem of fastbpe has been solved, thanks a lot,

but when i tried to re-run the command: ./bucc.sh, new problem occurred (it seems i did not have the 'models' directory and realted files, ):
it says that:


Processing BUCC data in .
2022-07-13 15:50:19,653 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
2022-07-13 15:50:19,913 | INFO | embed | loading encoder: home/LASER/models/bilstm.93langs.2018-12-26.pt
Traceback (most recent call last):
  File "home/LASER/source/embed.py", line 630, in <module>
    sort_kind=args.sort_kind,
  File "home/LASER/source/embed.py", line 503, in embed_sentences
    cpu=cpu,
  File "home/LASER/source/embed.py", line 368, in load_model
    encoder, spm_vocab=spm_vocab, verbose=verbose, **encoder_kwargs
  File "home/LASER/source/embed.py", line 86, in __init__
    state_dict = torch.load(model_path)
  File "home/opt/anaconda3/envs/laser/lib/python3.6/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "home/opt/anaconda3/envs/laser/lib/python3.6/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "home/opt/anaconda3/envs/laser/lib/python3.6/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'home/LASER/models/bilstm.93langs.2018-12-26.pt'

**Comment by heffernankevin** [comment]
Can you try running the model download script located [here](https://github.com/facebookresearch/LASER/blob/main/install_models.sh)?

**Comment by heffernankevin** [comment]
Closing as main issue has been solved and remaining comment is related to a `faiss` library install.
