### ISSUE TITLE
similarity.py is missing 

### ISSUE THREAD

**Issue by 91ns** [facebookresearch/LASER#23]
I'm trying to install and run the similarity task but I got this error:

`bash ./wmt.sh
`
`python3: can't open file '/LASER//source/similarity_search.py': [Errno 2] No such file or directory`

**Comment by 91ns** [comment]
When trying to run the script similarity_search.py separately I'm getting this error:

```
Traceback (most recent call last):
  File "LASER/source/similarity_search.py", line 29, in <module>
    from embed import SentenceEncoder, EncodeLoad, EncodeFile
  File "/content/LASER/source/embed.py", line 36, in <module>
    from text_processing import Token, BPEfastApply
ModuleNotFoundError: No module named 'text_processing'
```
