### ISSUE TITLE
Bug Report: Issue when embedding in docker container

### ISSUE THREAD

**Issue by FavorMylikes** [facebookresearch/LASER#240]
## Issue 

```console
(env) root@7b8c194bd840:/app# $LASER/tasks/embed/embed.sh test.txt en
2023-07-25 10:53:40,954 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
2023-07-25 10:53:41,329 | INFO | embed | spm_model: /app/models/laser2.spm
2023-07-25 10:53:41,329 | INFO | embed | spm_cvocab: /app/models/laser2.cvocab
2023-07-25 10:53:41,329 | INFO | embed | loading encoder: /app/models/laser2.pt
2023-07-25 10:53:41,948 | INFO | preprocess | SPM processing test.txt  
Traceback (most recent call last):
  File "/app/LASER/source/embed.py", line 630, in <module>
    sort_kind=args.sort_kind,
  File "/app/LASER/source/embed.py", line 541, in embed_sentences
    over_write=False,
  File "/app/LASER/source/lib/text_processing.py", line 144, in SPMApply
    run(["/bin/bash", "-o", "pipefail", "-c", command], check=True, capture_output=True)
  File "/opt/conda/envs/env/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

## Key code

https://github.com/facebookresearch/LASER/blob/5b9820b0a632df9bb4a5195e002024b3b4227a30/docker/Dockerfile#L5

https://github.com/facebookresearch/LASER/blob/5b9820b0a632df9bb4a5195e002024b3b4227a30/source/lib/text_processing.py#L144

## Explanation

This parameter `capture_output` is added till Python 3.7, need a update for the `Dockerfile`

## Reference

[Python doc 3.7](https://docs.python.org/3.7/library/subprocess.html#subprocess.run)

**Comment by avidale** [comment]
@FavorMylikes The docker app has been updated in #251.
It should work properly now.
