### ISSUE TITLE
assertion error 

### ISSUE THREAD

**Issue by Stolaine** [facebookresearch/LASER#33]
while running bash ./xnli.sh i am getting this error
Traceback (most recent call last):
  File "/home/appuser/sheshank.k/projects/laser/source/nli.py", line 228, in <module>
    dim=args.dim, bsize=args.bsize, shuffle=True)
  File "/home/appuser/sheshank.k/projects/laser/source/nli.py", line 57, in LoadDataNLI
    D = data_utils.TensorDataset(torch.from_numpy(nli), torch.from_numpy(lbl))
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 36, in __init__
    assert all(tensors[0].size(0) == tensor.size(0) for tensor in tensors)
AssertionError

**Comment by hoschwenk** [comment]
I suppose that the embeddings were not calculated correctly, and consequently, you get a size mismatch with the class target file.
This is probably related to #9 , i.e. the fastBPE command was not in the path.
Please pull the latest source and try again (removing spurious files)

**Comment by Stolaine** [comment]
@hoschwenk I have the latest source and the modification mentioned in #9 is also done. But the error is still there.

**Comment by DimitriTro** [comment]
I tied this solution, it solved a part of the problem, but this one still remain : 

Training the classifier (see embed/xnli.log)
Traceback (most recent call last):
  File "/home/trotignon/projects/LASER/source/nli.py", line 228, in <module>
    dim=args.dim, bsize=args.bsize, shuffle=True)
  File "/home/trotignon/projects/LASER/source/nli.py", line 57, in LoadDataNLI
    D = data_utils.TensorDataset(torch.from_numpy(nli), torch.from_numpy(lbl))
  File "/home/trotignon/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 36, in __init__
    assert all(tensors[0].size(0) == tensor.size(0) for tensor in tensors)
AssertionError

Even with the last version,
Thank you

**Comment by hoschwenk** [comment]
Indeed, it looks like that the XNLI link is broken or was moved elsewhere.
Sadly, I can't help you with this. If there is no data, the tool won't work :-)
Please have a look at the size of the created files - I guess that there is an error somewhere.

**Comment by DimitriTro** [comment]
Thank you very much, will look at it!
