### ISSUE TITLE
BUCC task: IndexError related to neighborhood size and number of source/target sentences

### ISSUE THREAD

**Issue by prokopidis** [facebookresearch/LASER#57]
Hi and thank you for releasing the LASER code. 

It seems that the `mine_bitexts.py` throws index errors like the following when either or both of the documents to be examined have fewer unique sentences than the `args.neighborhood` argument passed to the `knn` function.  

```
LASER: tool to search, score or mine bitexts
 - knn will run on all available GPUs (recommended)
 - loading texts /data/test/el/AD/599030.sent: 4 lines, 4 unique
 - loading texts /data/test/en/EX/57568553.sent: 2 lines, 2 unique
 - unify embeddings: 4 -> 4
 - unify embeddings: 2 -> 2
 - perform 4-nn source against target
Traceback (most recent call last):
  File "/opt/LASER//source/mine_bitexts.py", line 226, in <module>
    x2y_sim, x2y_ind = knn(x, y, args.neighborhood, args.gpu)
  File "/opt/LASER//source/mine_bitexts.py", line 74, in knn
    return knnGPU(x, y, k) if use_gpu else knnCPU(x, y, k)
  File "/opt/LASER//source/mine_bitexts.py", line 106, in knnGPU
    sim[i, j] = bsims[i-xfrom, aux[i-xfrom, j]]
IndexError: index 2 is out of bounds for axis 1 with size 2
```

A workaround would perhaps be to call the `knn` function like

```
x2y_sim, x2y_ind = knn(x, y, min(len(y), args.neighborhood), args.gpu) # source against target
y2x_sim, y2x_ind = knn(y, x, min(len(x), args.neighborhood), args.gpu) # target against source
```

**Comment by hoschwenk** [comment]
done
