### ISSUE TITLE
ValueError: could not convert string to float: '0CAT'

### ISSUE THREAD

**Issue by tonytonyissaissa** [facebookresearch/LASER#77]
Hi,
I am trying to reproduce the experiment of text classification by executing the script ./mldoc.sh. However, when training starts I got this kind of error:
Training MLDoc classifier (log files in embed)
 - train on en, dev on en
Traceback (most recent call last):
  File "LASER/source/sent_classif.py", line 188, in <module>
    dim=args.dim, bsize=args.bsize, shuffle=True)
  File "LASER/source/sent_classif.py", line 34, in LoadData
    lbl = np.loadtxt(bdir + lfn, dtype=np.int32)
  File "/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1141, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1068, in read_data
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1068, in <listcomp>
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/lib/python3.6/site-packages/numpy/lib/npyio.py", line 785, in <lambda>
    return lambda x: int(float(x))
ValueError: could not convert string to float: '0CAT'

**Comment by tonytonyissaissa** [comment]
OK. I think I have to run sampling_rcv2.py before going into training or change line 53 in mldoc.sh to:
sed -e 's/CCAT/0/' -e 's/ECAT/1/' -e 's/GCAT/2/' -e 's/MCAT/3/' \
